package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class ManageUserUtilityController {
	@FXML
	private TextField txtCustomerID;
	@FXML
	private TextField txtUtilityType;
	@FXML
	private TextField txtIncidentStatus;
	@FXML
	private TextField txtIncidentDescription;
	@FXML
	private TextField txtGenerateIncident;
	@FXML
	private Button btnBack;
	@FXML
	private Button btnClear;
	@FXML
	private Button btnInsert;

	// Event Listener on Button[#btnBack].onAction
	@FXML
	public void handleBackButton(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnClear].onAction
	@FXML
	public void handleClearButton(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnInsert].onAction
	@FXML
	public void handleInsertButton(ActionEvent event) {
		// TODO Autogenerated
	}
}
